
http:
  routers:
    frontend:
      rule: "Host(`localhost`) && PathPrefix(`/foo`)"
      service: frontend
      entryPoints:
        - "web"
      middlewares:
        - "redirectregex-frontend"
    backend:
      rule: "Host(`localhost`) && PathPrefix(`/api`)"
      service: backend
      entryPoints:
        - "web"
    esb:
      rule: "Host(`localhost`) && PathPrefix(`/api-esb`)"
      service: esb
      entryPoints:
        - "web"
      middlewares:
        - "redirectregex-esb"
  services:
    frontend:
      loadBalancer:
        servers:
#          - url: http://myhost:3005/
#          - url: http://192.168.178.180:3005
          - url: http://127.0.0.1:3005
#          - url: http://192.168.178.1:80
    backend:
      loadBalancer:
        servers:
          - url: http://localhost:8081/
    esb:
      loadBalancer:
        servers:
          - url: srvscs1-test.atupri.ch

  middlewares:
    redirectregex-frontend:
      redirectregex:
        regex: "^http://localhost/foo"
        replacement: "http://myhost:3005"
    redirectregex-esb:
      redirectregex:
        regex: "^http://localhost/api-esb"
        replacement: "https://srvscs1-test.atupri.ch:9960"
